services:
  - type: worker
    name: medusaxd-tts-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
      - key: REDIS_URL
        fromService:
          type: redis
          name: medusaxd-tts-bot-redis
          property: connectionString
    # Removed scaling configuration for simple single-instance deployment
    
  - type: redis
    name: medusaxd-tts-bot-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: [] # Allow all IPs (empty list means no restrictions)
